### ISSUE TITLE
can't download plugin 

### ISSUE THREAD

**Issue by vadymchan** [djmango/obsidian-transcription#18]
when i try to download the plugin, i have an error:

![image](https://github.com/djmango/obsidian-transcription/assets/98042439/bf80dd28-9941-4ce1-9075-7fda3330bfac)

![image](https://github.com/djmango/obsidian-transcription/assets/98042439/84c4b8bb-7df0-43c4-91fa-432ff1f7899b)

**Comment by djmango** [comment]
Hey @vadymchan, thanks for coming to me with this. Could you provide some details about your environment and context so I can replicate and fix?

1. Are you able to download other plugins?
2. What version of Obsidian are you using?
3. What platform? (iOS, Mac, Linux, etc)
4. What happens when you open a fresh vault and install the plugin from there?

**Comment by boymaas** [comment]
Hey @djmango, thanks for creating the plugin. I am running into the same issue. Using Obsidian 1.3.5 on a Mac.

**Comment by vadymchan** [comment]
Hi. Thank you for your response! Sure. So:
1) Yes, I have successfully downloaded and installed other plugins without encountering any problems.
2) I'm using v1.3.5
3) Windows 11
4) still unable to download =(

**Comment by djmango** [comment]
Should be good to go now, thanks again for letting me know!

**Comment by vadymchan** [comment]
Yep, now I've successfully downloaded the plugin. Thanks a lot for your quick fix and for making this plugin in the first place!
