### ISSUE TITLE
Any way to make transcripts for audios/videos that aren't stored in the vault? 

### ISSUE THREAD

**Issue by jorge42222** [djmango/obsidian-transcription#26]
Hello!

I tried to transcribe an audio that isn't stored in the vault
tried it in 2 formats
```()[<file:///path_to_audio.mp3>]``` and ```<audio src="file:///path_to_audio.mp3" controls></audio>```
And the plugin didn't recognize it

Is it possible in the current version of the plugin, or if not I think it would be a good feature request since storing long videos in obsidian isn't really a good thing if you use obsidian on multiple devices

**Comment by djmango** [comment]
Currently we're using Obsidian/Electrons API to read files, which only has permission to read within the vault. There may be a way to read from the external filesystem, but unsure of how permissions will work on mobile. Educated guess would be that it's not a problem if an API in Obsidian that can read globally exists at all, since the Obsidian app can already read the files.

Will explore later this week.

**Comment by djmango** [comment]
This should now work in 3.2.2. Let me know if you have any issues
