### ISSUE TITLE
Find audio if the file is inside code block

### ISSUE THREAD

**Issue by dxcore35** [djmango/obsidian-transcription#9]
Hello!

For example also here the audio file is inside the code block:

![Screenshot 2023-01-22 at 12 40 24](https://user-images.githubusercontent.com/7279156/213911673-39d9bed8-b429-46d2-b801-bcbfe9efc9d8.jpg)

And when trying to execute the transcription, your plugin will not detect that there is and audio file.

Could you please send also code blocks for audio?

**Comment by djmango** [comment]
Looks like this is caused due to the fact that Obsidian itself can't recognize that the file is linked - the [plugin](https://github.com/noonesimg/obsidian-audio-player) @noonesimg will have to ensure that the files in their custom code blocks are linked in Obsidian's standard and added to `app.metadataCache.resolvedLinks`.

Closing since this issue is out of scope for Transcription - I can offer some help to @noonesimg to solve this issue on their end if so desired.
